/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { BufferGeometry, Mesh, NormalBufferAttributes, Object3D, Object3DEventMap } from 'three'



export function Planet1(props:any) {
  const group = useRef()
  const cloudRef = useRef<Mesh<BufferGeometry<NormalBufferAttributes>>>()
  const planetRef = useRef<Mesh<BufferGeometry<NormalBufferAttributes>>>()
  useFrame((state,delta)=>{
    if(cloudRef.current)
        cloudRef.current.rotation.y+=delta/2;
    if(planetRef.current)
        planetRef.current.rotation.y+=delta/4;
  })
  const { nodes, materials } = useGLTF('./assets/planet1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={2.2} position={[0,0,-1]} name="Scene">
        <mesh
          ref={planetRef}
          name="planet_continental"
          castShadow
          receiveShadow
          geometry={nodes.planet_continental.geometry}
          material={materials.Planet_continental}
        />
        <mesh
          ref={cloudRef}
          name="planet_continental_clouds"
          castShadow
          receiveShadow
          geometry={nodes.planet_continental_clouds.geometry}
          material={materials.planet_continental_cloud}
          scale={0.968}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./assets/planet1.gltf')