/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { BufferGeometry, Mesh, NormalBufferAttributes } from 'three'

export function Planet2(props:any) {
  const group = useRef()
  const cloudRef = useRef<Mesh<BufferGeometry<NormalBufferAttributes>>>()
  const planetRef = useRef<Mesh<BufferGeometry<NormalBufferAttributes>>>()
  useFrame((state,delta)=>{
    if(cloudRef.current)
        cloudRef.current.rotation.y+=delta/2;
    if(planetRef.current)
        planetRef.current.rotation.y+=delta/4;
  })
  const { nodes, materials, animations } = useGLTF('./assets/planet2.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group  scale={2} position={[0,-6,-2]} name="Scene">
        <mesh
          ref={planetRef}
          name="planet_smac"
          castShadow
          receiveShadow
          geometry={nodes.planet_smac.geometry}
          material={materials.Planet_smac}
        />
        <mesh
          ref={cloudRef}
          name="planet_smac_cloud"
          castShadow
          receiveShadow
          geometry={nodes.planet_smac_cloud.geometry}
          material={materials.planet_smac_cloud}
          scale={0.975}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./assets/planet2.gltf')