/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Planet3(props:any) {
  const group = useRef()
  const cloudRef = useRef()
  const cloud2Ref = useRef()
  const planetRef = useRef()
  useFrame((state,delta)=>{
    if(cloudRef.current)
      cloudRef.current.rotation.y+=delta/2;
  if(planetRef.current)
      planetRef.current.rotation.y+=delta/4;
  })
  const { nodes, materials } = useGLTF('./assets/planet3.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group  scale={2.4} position={[0,-12,-4]} name="Scene">
      <mesh
          ref={planetRef}
          name="planet_gas"
          castShadow
          receiveShadow
          geometry={nodes.planet_gas.geometry}
          material={materials.planet_gas}
        />
           <mesh
          ref={cloudRef}
          name="planet_gas_cloud_01"
          castShadow
          receiveShadow
          geometry={nodes.planet_gas_cloud_01.geometry}
          material={materials.planet_gas_cloud_01}
          scale={0.962}
        />
      </group>
    </group>
  )
}

