/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, Vector3 } from "@react-three/fiber";
import { BufferGeometry, Mesh, NormalBufferAttributes } from "three";

export function Planet(props: {
  model: string;
  position?: Vector3;
  scale?: number;
}) {
  const { nodes, materials } = useGLTF<string>(props.model);
  const planetRef = useRef<Mesh<BufferGeometry<NormalBufferAttributes>>>();
  useFrame((state, delta) => {
    if (planetRef.current) {
      planetRef.current.rotation.y += delta / 12;
      planetRef.current.rotation.z += delta / 48;
    }
  });
  return (
    <group
      position={props.position ?? [0, 0, 0]}
      scale={props.scale ?? 1}
      dispose={null}
    >
      <mesh
        ref={planetRef}
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
      />
    </group>
  );
}
