/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useThree } from '@react-three/fiber'

export function Planet6(props:any) {
  const group = useRef()
  const planetRef = useRef()

  useFrame((state,delta)=>{
    if(planetRef.current)
        planetRef.current.rotation.y+=delta/4;
  })
  const { nodes, materials, animations } = useGLTF('./assets/planet6.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group  scale={1.9} position={[0,-30,-2]} name="Scene">
      <mesh
          ref={planetRef}
          name="planet_lava"
          castShadow
          receiveShadow
          material={materials.Planet_lava}
        >
          <sphereGeometry args={[1,16]}/>
        </mesh>
      </group>
    </group>
  )
}

