/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Planet4(props:any) {
  const group = useRef()
  const planetRef = useRef()
  useFrame((state,delta)=>{
    if(planetRef.current)
        planetRef.current.rotation.y+=delta/4;
  })
  const { nodes, materials, animations } = useGLTF('./assets/planet4.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group  scale={2} position={[0,-18,-1]} name="Scene">
      <mesh
          ref={planetRef}
          name="planet_barren"
          castShadow
          receiveShadow
          material={materials.Planet_barren}
        >
          <sphereGeometry args={[1,16]}/>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('./assets/planet4.gltf')