/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Spaceship = forwardRef(function Spaceship(props, ref) {
  const { nodes, materials } = useGLTF("./assets/spaceship.gltf");
  return (
    <group {...props} ref={ref} dispose={null}>
      <group scale={0.01}>
        <group scale={0.2}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_s_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_s_0001.geometry}
            material={materials.material}
          />
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("./assets/spaceship.gltf");
